### ISSUE TITLE
Can't find cytof tutorial anymore

### ISSUE THREAD

**Issue by synatkeamsk** [markrobinsonuzh/cytofWorkflow#33]
Dear Authors, 

I am trying to read the tutorial of CYTOF in Bioconductor. but it kept receiving the page was not found since yesterday. Not sure whether the tutorial was removed. 

Kind Regards,

Synat, 
![Capture_1](https://github.com/markrobinsonuzh/cytofWorkflow/assets/121846660/245553c8-2c1e-433a-986e-99695d393acc)
![Capture](https://github.com/markrobinsonuzh/cytofWorkflow/assets/121846660/f3f27a5c-670a-4c31-a06d-5f60da5190c8)
![Capture_3](https://github.com/markrobinsonuzh/cytofWorkflow/assets/121846660/edf9c20e-3dee-4dc9-8db4-00c0f6f1d9f2)

**Comment by HelenaLC** [comment]
Probably something to do with Bioc 3.18 having been released yesterday. I can see the workflow‘s landing page [here](https://www.bioconductor.org/packages/release/workflows/html/cytofWorkflow.html), but it seems the html hadn‘t been built yet. Should fix itself over the next couple days, I hope. 

In the meantime, the corresponding F1000Research article and/or CATALYST package vignette provide great resources that you could consult instead (same info, different format/lengths I‘d say).

**Comment by markrobinsonuzh** [comment]
I think this is related to a web server problem (where we retrieve some metadata) we are having, and I'm working on a fix, but it will indeed take a couple days to propagate to the latest release/devel versions.

In the meantime, you can access the bioC 3.17 version here:
https://bioconductor.org/packages/3.17/workflows/vignettes/cytofWorkflow/inst/doc/cytofWorkflow.html

There has been no code changes, so the same code should work on Bio 3.18 and devel. The needed metadata can be downloaded from here:
https://zenodo.org/records/10039274

**Comment by markrobinsonuzh** [comment]
OK, I've committed a fix to the RELEASE_3_18 branch .. hopefully it'll clear up in a couple of days.

**Comment by markrobinsonuzh** [comment]
Also to `devel`, tested it locally, will close the issue .. if I still get an error message, will re-open.
